# Generated by Django 3.0 on 2020-01-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20200102_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_url',
            field=models.CharField(default='/', max_length=100, verbose_name='url'),
        ),
    ]
