# Generated by Django 3.0 on 2020-01-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20200102_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='solved_list',
            field=models.CharField(default='default', max_length=15000),
        ),
    ]
