# Generated by Django 3.0 on 2020-01-03 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_auto_20200102_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PTIT', max_length=100, verbose_name='name')),
                ('score', models.FloatField(default=1, verbose_name='score')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.Problem')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.User')),
            ],
        ),
    ]
