# Generated by Django 3.0 on 2020-01-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_problem_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='solved_list',
        ),
    ]
