# Generated by Django 3.0 on 2020-01-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0006_remove_user_solved_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='duchanhctn99', max_length=100, verbose_name='user name'),
        ),
    ]
